---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ns-ui-2
  labels:
    app: lab-ns-2
    service: lab-ns
    component: lab-ns-ui
spec:
  ingressClassName: nginx
  rules:
  - host: ns2.apps.k8s.kemo.labs
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: lab-ns-2-ui
            port:
              number: 80