apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab-ns-2

resources:
  - ../../base/
  - namespace.yml
  - pvc-ui.yml
  - configmap-recursor-server.yml
  - deployment-auth.yml
  - deployment-recursor.yml
  - deployment-ui.yml
  - services.yml
  - ingress-ui.yml
