---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdns-2-ui-data
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: bulk-ssd
  resources:
    requests:
      storage: 1Gi
