---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab-dns-mysql

resources:
  - namespace.yml
  - service.yml
  - statefulset.yml
  - schema-sync-job-rbac.yml
  - schema-sync-job.yml
  - networkpolicy.yml
  - pvc.yml