---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pdns-mysql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  podSelector:
    matchLabels:
      app: lab-pdns-mysql
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              service: lab-nss
        - podSelector:
            matchLabels:
              component: lab-ns-auths
      ports:
        - protocol: TCP
          port: 3306