---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lab-dns-mysql-sync-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lab-dns-mysql-sync-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - exec
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lab-dns-mysql-sync-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lab-dns-mysql-sync-job
subjects:
  - kind: ServiceAccount
    name: lab-dns-mysql-sync-job
    namespace: lab-dns-mysql