name: Build Container - MySQL
on:
  push:
    branches:
      - main
    paths:
      - Containerfile.mysql
      - .github/workflows/build-mysql-container.yml

  # Schedule workflow run at 00:00 on Sunday
  schedule:
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build the container
  build-container:
    name: Build Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 30
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64,amd64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          ghcr.io/kenmoini/lab-powerdns
        # generate Docker tags based on the following events/attributes
        tags: |
          type=schedule,prefix=mysql-
          type=ref,prefix=mysql-,event=branch
          type=ref,prefix=mysql-,event=tag
          type=sha,prefix=mysql-,suffix=,format=short
          type=sha,prefix=mysql-,suffix=,format=long
          type=raw,value=mysql-latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: "${{ github.actor }}"
        password: "${{ secrets.GITHUB_TOKEN }}"

    - name: Login to Red Hat Container Registry
      uses: docker/login-action@v3
      with:
        registry: registry.redhat.io
        username: "${{ secrets.RH_REGISTRY_USERNAME }}"
        password: "${{ secrets.RH_REGISTRY_TOKEN }}"

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Containerfile.mysql
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        push: true
        #cache-from: type=gha
        #cache-to: type=gha,mode=max
        #platforms: linux/amd64, linux/arm64